#ifndef ERRCODES_H_
#define ERRCODES_H_
#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    NO_RESERVE_SECTORS_ERROR,
    DSK_SETUP_ERROR,
    MALLOC_ERROR,
    DSK_READ_SECTOR_ERROR,
    CHECKSUM_CHECK_ERROR,
    FATCACHE_INIT_ERROR,
    FATCACHE_HINIT_ERROR,
    CTABLE_INIT_ERROR,
    JOURNAL_RESTORE_ERROR,
    ADD_ENTRY_ERROR,
    SET_CLUSTER_END_ERROR,
    CTABLE_FULL_ERROR,
    ENTRY_PATH_NFOUND_ERROR,
    CONTENT_INDEX_ERROR,
    NO_READ_ACCESS_ERROR,
    NO_WRITE_ACCESS_ERROR,
    READOFF_CLUSTER_ERROR,
    WRITEOFF_CLUSTER_ERROR,
    READ_CLUSTER_ERROR,
    WRITE_CLUSTER_ERROR,
    WRITE_FAT_ERROR,
    READ_FAT_ERROR,
    SECTOR_READ_ERROR,
    SECTOR_WRITE_ERROR,
    ALLOCATED_CLUSTER_BAD_ERROR,
    CLUSTER_ALLOCATION_ERROR,
    ENTRY_EDIT_ERROR,
    ENTRY_SEARCH_ERROR,
    ENTRY_ADD_ERROR,
    ENTRY_REMOVE_ERROR,
    COPY_CLUSTER_ERROR,
    UNKNOWN_DEEP_TYPE_ERROR,
    REPAIR_CONTENT_ERROR,
    ERROR_CORRECTION_ERROR,
    BAD_CLUSTER_IN_CHAIN_ERROR,
    RECURSIVE_ERASE_ERROR,
    CLUSTER_DEALLOCATION_ERROR,
    CLUSTER_CHAIN_DELETION_ERROR,
    CLUSTER_CHAIN_APPEND_ERROR,
    JOURNAL_WRITE_ERROR,
    JOURNAL_READ_ERROR,
    READLOCK_SECTOR_ERROR,
    READLOCK_CLUSTER_ERROR,
    WRITELOCK_SECTOR_ERROR,
    WRITELOCK_CLUSTER_ERROR,
    DISK_IO_WRITE_ERROR,
    DISK_IO_READ_ERROR
} error_code_t;

#ifdef __cplusplus
}
#endif
#endif